### PR TITLE
Better model

### PR DESCRIPTION
**Pull request by FrancescaCrucinio**
I updated the file to build the functions to logistic regression.

I reduced the number of inputs for LogLikelihood, LogBound etc.
map.tuned, scale, mu and t are now properties of the model and should not be passed as inputs at each call
As a consequence we do not need to check for the number of arguments in every other function (e.g. nargs()==... can be deleted)

I think it would be a nice idea to make the model functions global in the fireflyMC script, so that we can recall them easily

### CODE REVIEW

**Comment by TomasVaskevicius** [comment]
Hi Francesca, 

I am now working on the same thing and have made changes to most of the logistic regression model file, which I think had incorrect implementations at some places (?).

Also, could you please check what is wrong with your local version of git? Because you keep submitting the same commits in your pull requests, i.e. there are 10 commits in this one.

Tomas

**Comment by TomasVaskevicius** [comment]
To fix your local master branch, run

git checkout master
git reset --hard origin/master
git pull origin master

**Comment by FrancescaCrucinio** [comment]
--I am now working on the same thing and have made changes to most of the logistic regression model file, which I think had incorrect implementations at some places (?).

Ok! We can take a look at this Tomorrow, as everything runs smoothly in my laptop (and in my mind).
Or if you can share your changes I'll take a look.

--Also, could you please check what is wrong with your local version of git? Because you keep submitting the same commits in your pull requests, i.e. there are 10 commits in this one.

I saw that something went wrong but honestly I've no idea on how to fix it!
I'll try the commands in your comment ;)

Cheers,

Francesca

**Comment by FrancescaCrucinio** [comment]
Hi Tomas,

could you tell me which functions are not correct?
As I am going through the logistic script checking if it works and I only found 1 error in the map tuned version...

Thanks,

Francesca

**Comment by TomasVaskevicius** [comment]
Check my latest pull request for comments.
I think the way constant "a" was calculated was wrong, and also the log posterior was not computed efficiently.

**Pull request closed without merging**
